version: "3.9"

services:
  movies-db:
    image: postgres:15
    container_name: movies-db
    env_file:
      - .env
    ports:
      - "5432:5432"
  movies-app:
    build: .
    container_name: movies-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - movies-db
